{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Hardware", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "total_power_watts", "legendFormat": "Total power" }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "J/TH" } },
   "targets": [
    { "expr": "total_efficiency", "legendFormat": "Average efficiency" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_hardware", "legendFormat": "Total hardware" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hardware_online", "legendFormat": "Hardware online" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hardware_offline", "legendFormat": "Hardware offline" }
   ]
  },
  {
   "title": "Timeline & Average Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "GH/s" } },
   "targets": [
    { "expr": "total_hashrate", "legendFormat": "Total hashrate" }
   ]
  },
  {
   "title": "Firmware Fragmentation",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "firmware_version_distribution", "legendFormat": "{{version}}" }
   ]
  }
 ]
}