{
 "title": "@@hostname@@",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GH/s" } },
   "targets": [
    { "expr": "@@hostname@@_hashrate_ghs", "legendFormat": "Hashrate" }
   ]
  },
  {
   "title": "Power Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "targets": [
    { "expr": "@@hostname@@_power_watts", "legendFormat": "Power" }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "J/TH" } },
   "targets": [
    {
     "expr": "@@hostname@@_power_watts/(@@hostname@@_hashrate_ghs/1000)",
     "legendFormat": "Average efficiency"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "@@hostname@@_temperature_celsius",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_fanspeed_rpm", "legendFormat": "Fan speed" }
   ]
  },
  {
   "title": "Core Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "@@hostname@@_core_voltage_actual_volts",
     "legendFormat": "Core Actual Voltage"
    },
    {
     "expr": "@@hostname@@_core_voltage_volts",
     "legendFormat": "Core Voltage"
    },
    { "expr": "@@hostname@@_voltage_volts", "legendFormat": "Voltage" }
   ]
  }
 ]
}