# Stage 1: Build
FROM node:24-alpine AS builder

# Set the working directory
WORKDIR /home/node/app

# Copy the entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Change ownership to allow access for the `node` user
RUN chown -R node:node /home/node

# Switch to the `node` user
USER node

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

# Start the application
CMD ["npm", "run", "dev"]
