comment: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/coverage/**"
