services:
  app_proxy:
    environment:
      APP_HOST: plutomining-pluto-next_frontend_1
      APP_PORT: 7677
    depends_on:
      - frontend
    restart: on-failure

  mock:
    image: registry.gitlab.com/plutomining/pluto/pluto-mock:0.6.0-rc.1
    ports:
      - "7670:7670"
      - "7651:7651"
      - "7652:7652"
      - "7653:7653"
      - "7654:7654"
      - "7655:7655"
      - "7656:7656"
      - "7657:7657"
      - "7658:7658"
      - "7659:7659"
      - "7660:7660"
    pid: host
    restart: on-failure
    environment:
      - LISTING_PORT=7670
      - PORTS=7651,7652,7653,7654,7655,7656,7657,7658,7659,7660
      - LOGS_PUB_ENABLED=false
    user: "1000:1000"

  discovery:
    image: registry.gitlab.com/plutomining/pluto/pluto-discovery:0.6.0-rc.1
    network_mode: "host"
    pid: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: on-failure
    environment:
      - PORT=7675
      - DETECT_MOCK_DEVICES=true
      - MOCK_DISCOVERY_HOST=http://172.17.0.1:7670
    volumes:
      - ${APP_DATA_DIR}/data/leveldb:/home/node/app/data
    user: "1000:1000"

  backend:
    image: registry.gitlab.com/plutomining/pluto/pluto-backend:0.6.0-rc.1
    pid: host
    restart: on-failure
    environment:
      - PORT=7676
      - AUTO_LISTEN=true
      - DISCOVERY_SERVICE_HOST=http://172.17.0.1:7675
      - GF_HOST=http://plutomining-pluto-next_grafana_1:3000
      - DELETE_DATA_ON_DEVICE_REMOVE=true
    volumes:
      - ${APP_DATA_DIR}/data/leveldb:/home/node/app/data
      - ${APP_DATA_DIR}/data/grafana:/home/node/app/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    user: "1000:1000"

  frontend:
    image: registry.gitlab.com/plutomining/pluto/pluto-frontend:0.6.0-rc.1
    pid: host
    restart: on-failure
    depends_on:
      - backend
    environment:
      - PORT=7677
      - GF_HOST=http://plutomining-pluto-next_grafana_1:3000
      - BACKEND_DESTINATION_HOST=http://plutomining-pluto-next_backend_1:7676
    volumes:
      - ${APP_DATA_DIR}/umbrel-app.yml:/tmp/umbrel-app.yml:ro
    user: "1000:1000"

  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ${APP_DATA_DIR}/data/prometheus:/prometheus
      - ${APP_DATA_DIR}/data/conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    pid: host
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider --quiet http://localhost:9090/-/ready || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    user: "65534:65534"

  grafana:
    image: grafana/grafana:11.1.2
    pid: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${APP_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-treemap-panel
    volumes:
      - ${APP_DATA_DIR}/data/grafana:/var/lib/grafana
      - ${APP_DATA_DIR}/data/conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ${APP_DATA_DIR}/data/conf/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ${APP_DATA_DIR}/data/conf/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider --quiet http://localhost:3000/api/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
    user: "472:472"
