#!/usr/bin/env python3
"""
Export OpenAPI schema from FastAPI application.

This script exports the OpenAPI schema generated by FastAPI,
which serves as the single source of truth for API contracts.
The schema can be used to generate clients for multiple languages.

Usage:
    # From project root:
    python3 pyasic-bridge/scripts/export_openapi.py [output_path]
    
    # Or from pyasic-bridge directory:
    cd pyasic-bridge
    python3 scripts/export_openapi.py [output_path]
    
    # If Poetry is configured (pyproject.toml exists):
    cd pyasic-bridge
    poetry run python scripts/export_openapi.py [output_path]

Requirements:
    Install dependencies first:
        # Using venv (recommended for this project):
        cd pyasic-bridge
        make setup-pyasic-bridge
        # Or manually:
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        
        # If Poetry is configured:
        cd pyasic-bridge
        poetry install
"""

import json
import sys
from pathlib import Path

# Add app directory to path
script_dir = Path(__file__).parent
pyasic_bridge_dir = script_dir.parent
sys.path.insert(0, str(pyasic_bridge_dir))

# Check for Poetry and pyproject.toml
import subprocess
poetry_available = False
poetry_configured = False
try:
    result = subprocess.run(
        ["poetry", "--version"],
        capture_output=True,
        text=True,
        timeout=2
    )
    poetry_available = result.returncode == 0
    # Check if pyproject.toml exists (Poetry is configured for this project)
    poetry_configured = (pyasic_bridge_dir / "pyproject.toml").exists()
except (FileNotFoundError, subprocess.TimeoutExpired):
    pass

# Check for venv and suggest activation
venv_path = pyasic_bridge_dir / "venv"
in_venv = hasattr(sys, "real_prefix") or (hasattr(sys, "base_prefix") and sys.base_prefix != sys.prefix)

if poetry_configured and not in_venv:
    print("💡 Tip: Poetry detected. Consider using:", file=sys.stderr)
    print(f"   poetry run python {Path(__file__).relative_to(pyasic_bridge_dir)}", file=sys.stderr)
    print("   This will automatically use Poetry's virtual environment.\n", file=sys.stderr)
elif venv_path.exists() and not in_venv:
    print("💡 Tip: Virtual environment detected but not activated.", file=sys.stderr)
    print(f"   Activate it with: source {venv_path}/bin/activate", file=sys.stderr)
    print("   Or run: make setup-pyasic-bridge\n", file=sys.stderr)

# Check for required dependencies
try:
    from app.app import create_app
except ImportError as e:
    if "fastapi" in str(e).lower() or "ModuleNotFoundError" in str(type(e).__name__):
        print("❌ Error: FastAPI and dependencies are not installed.", file=sys.stderr)
        print("\nPlease install dependencies first:", file=sys.stderr)
        if poetry_configured:
            print(f"  cd {pyasic_bridge_dir}", file=sys.stderr)
            print("  poetry install", file=sys.stderr)
            print("  poetry run python scripts/export_openapi.py", file=sys.stderr)
        elif venv_path.exists():
            print(f"  source {venv_path}/bin/activate", file=sys.stderr)
            print("  pip install -r requirements.txt", file=sys.stderr)
        else:
            print(f"  cd {pyasic_bridge_dir}", file=sys.stderr)
            print("  make setup-pyasic-bridge  # Creates venv and installs deps", file=sys.stderr)
            print("  # Or manually:", file=sys.stderr)
            print("  python3 -m venv venv", file=sys.stderr)
            print("  source venv/bin/activate", file=sys.stderr)
            print("  pip install -r requirements.txt", file=sys.stderr)
        sys.exit(1)
    raise


def export_openapi_schema(output_path: Path) -> None:
    """
    Export OpenAPI schema from FastAPI app.

    Args:
        output_path: Path where to save the OpenAPI JSON schema
    """
    app = create_app()
    openapi_schema = app.openapi()

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write schema to file
    with open(output_path, "w") as f:
        json.dump(openapi_schema, f, indent=2, default=str)

    print(f"✅ OpenAPI schema exported to: {output_path}")
    print(f"   - {len(openapi_schema.get('paths', {}))} endpoints")
    print(f"   - {len(openapi_schema.get('components', {}).get('schemas', {}))} schemas")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])
    else:
        # Default: export to common/contracts directory
        output_path = Path(__file__).parent.parent.parent / "common" / "contracts" / "pyasic-bridge-openapi.json"

    export_openapi_schema(output_path)
