#!/bin/sh

# Imposta permessi di scrittura per LevelDB sulla directory /leveldb
echo "Setting permissions for LevelDB data directory..."

mkdir -p ${APP_DATA_DIR}/data/leveldb
chown -R umbrel:umbrel ${APP_DATA_DIR}/data/leveldb
chmod -R 777 ${APP_DATA_DIR}/data/leveldb

# Stampa i permessi per confermare
ls -ld ${APP_DATA_DIR}/data/leveldb

echo "LevelDB permissions set successfully!"

echo "Setting permissions for Prometheus data directory..."

mkdir -p ${APP_DATA_DIR}/data/prometheus
chown -R umbrel:umbrel ${APP_DATA_DIR}/data/prometheus
chmod -R 777 ${APP_DATA_DIR}/data/prometheus

# Stampa i permessi per confermare
ls -ld ${APP_DATA_DIR}/data/prometheus

echo "Prometheus permissions set successfully!"
