datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://bemind-pluto-next_prometheus_1:9090
    isDefault: true
    uid: PBFA97CFB590B2093
    jsonData:
      httpMethod: POST
