FROM grafana/grafana:11.1.2
COPY grafana.ini /etc/grafana/grafana.ini
COPY dashboard.yaml /etc/grafana/provisioning/dashboards/main.yaml
COPY datasource.yaml /etc/grafana/provisioning/datasources/main.yaml