{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Hardware",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_hardware", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hardware Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hardware_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hardware Offline",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hardware_offline", "legendFormat": "__auto" }
   ]
  },
  { "title": "Hashrate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Hashrate (GH/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_hashrate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Hashrate (GH/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "average_hashrate", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Shares by Pool",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shares_by_pool_accepted", "legendFormat": "{{pool}} Accepted" },
    { "expr": "shares_by_pool_rejected", "legendFormat": "{{pool}} Rejected" }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Power (W)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Efficiency (W/TH)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_efficiency", "legendFormat": "__auto" }
   ]
  },
  { "title": "Firmware Fragmentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Firmware Fragmentation",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    { "expr": "firmware_version_distribution", "legendFormat": "{{version}}" }
   ]
  }
 ]
}