{
 "title": "@@hostname@@",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Hashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hashrate (GH/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "@@hostname@@_hashrate_ghs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shares Accepted",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_shares_accepted", "legendFormat": "Accepted" }
   ]
  },
  {
   "title": "Shares Rejected",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_shares_rejected", "legendFormat": "Rejected" }
   ]
  },
  {
   "title": "Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "@@hostname@@_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Heap (Bytes)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_free_heap_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature (C)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "@@hostname@@_temperature_celsius",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Current (A)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_current_amps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Core Frequency (MHz)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_frequency_mhz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Core Actual Voltage (V)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "@@hostname@@_core_voltage_actual_volts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed (RPM)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "@@hostname@@_fanspeed_rpm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Core Required Voltage (V)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "@@hostname@@_core_voltage_volts",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}